### ISSUE TITLE
db error

### ISSUE THREAD

**Issue by CreedoW** [parasop/discord.js-bot-v12#8]
creedow@0x2b:~/x$ node index.js 
.-----------------------------.
|          Commands           |
|-----------------------------|
|    Command    | Load status |
|---------------|-------------|
| help.js       | ✅           |
| ping.js       | ✅           |
| setwelcome.js | ✅           |
'-----------------------------'
Your app is listening on port 44271
Hi, config is now online!
node:events:346
      throw er; // Unhandled 'error' event
      ^

MongooseServerSelectionError: connect ECONNREFUSED 127.0.0.1:27017
    at NativeConnection.Connection.openUri (/home/creedow/x/node_modules/mongoose/lib/connection.js:845:32)
    at Mongoose.createConnection (/home/creedow/x/node_modules/mongoose/lib/index.js:285:17)
    at Database._create (/home/creedow/x/node_modules/quickmongo/src/Base.js:66:25)
    at new Base (/home/creedow/x/node_modules/quickmongo/src/Base.js:38:32)
    at new Database (/home/creedow/x/node_modules/quickmongo/src/Main.js:21:9)
    at Object.<anonymous> (/home/creedow/x/index.js:15:13)
    at Module._compile (node:internal/modules/cjs/loader:1092:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1121:10)
    at Module.load (node:internal/modules/cjs/loader:972:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12)
    at node:internal/main/run_main_module:17:47
Emitted 'error' event on Database instance at:
    at NativeConnection.<anonymous> (/home/creedow/x/node_modules/quickmongo/src/Base.js:41:18)
    at NativeConnection.emit (node:events:369:20)
    at /home/creedow/x/node_modules/mongoose/lib/connection.js:854:37
    at processTicksAndRejections (node:internal/process/task_queues:76:11) {
  reason: TopologyDescription {
    type: 'Unknown',
    setName: null,
    maxSetVersion: null,
    maxElectionId: null,
    servers: Map(1) {
      'localhost:27017' => ServerDescription {
        address: 'localhost:27017',
        error: Error: connect ECONNREFUSED 127.0.0.1:27017
            at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1138:16) {
          name: 'MongoNetworkError'
        },
        roundTripTime: -1,
        lastUpdateTime: 1776156,
        lastWriteDate: null,
        opTime: null,
        type: 'Unknown',
        topologyVersion: undefined,
        minWireVersion: 0,
        maxWireVersion: 0,
        hosts: [],
        passives: [],
        arbiters: [],
        tags: []
      }
    },
    stale: false,
    compatible: true,
    compatibilityError: null,
    logicalSessionTimeoutMinutes: null,
    heartbeatFrequencyMS: 10000,
    localThresholdMS: 15,
    commonWireVersion: null
  }
}
creedow@0x2b:~/x$

**Comment by CreedoW** [comment]
this happened when i tried setwelcome command

**Comment by parasop** [comment]
Let me solve it
